# Selecting your research hypothesis

This chapter is based on a webpage I wrote in 1999.

## Step 1. Choose an outcome measure

Do you know, in a quantitative sense, how bad things are right now? If not, plan how you are going to measure yourself. In other words, define an outcome measure. Think about what other aspects of your patient care might be affected by the change and measure them also.

Then think about how you are going to measure the effects of your change. This is important. Sometimes you change things for the better, but sometimes your changes have no impact. It's even possible that your changes could make things worse instead of better.

## Step 2. Define your patient population

Insert text.

## Step 3. Select your control group

Insert text.

## The fly in the ointment

Insert text.

## Bibliography

Simon SD. Developing a research hypothesis. PMean blog, 1999-08-18. Available in [html format][ref03-simon-1999].

[ref03-simon-1999]: http://pmean.com/posts/steps-in-developing-research-hypothesis/
