---
title: "Word count"
execute: 
  echo: true
format:
  html:
    embed-resources: true
---

## Word counts

Here are the page counts for each chapter.

```{r}
#| message: false
#| warning: false
#| label: setup

library(glue)
library(stringr)
library(tidyverse)
```

```{r}
#| echo: true
#| label: page-counts

count_words <- function(fn) {
  read_lines(fn) |>
    paste0(collapse=" ") |>
    str_replace_all("[^a-z A-Z]", " ") |>
    str_replace_all(" +", "~") |> 
    str_split("~") |>
    unlist() |>
    length()
}

n <- count_words("../index.qmd")

file_list <- list.files(path="../chapters")
for (fn in file_list) {
  ni <- count_words(glue("../chapters/{fn}"))
  n <- append(n, ni)
}
n_total <- sum(n)
paste0("-   Chapter ", 0:length(file_list), ": ", n) |>
  str_replace_all("Chapter 0", "Preface") |>
  str_replace_all("Chapter 22", "Summary") |>
  str_replace_all("Chapter 23", "Bibliography") |>
  paste0(collapse="\n") -> chapter_count
write_lines(c(n_total, n), paste0(Sys.Date(), ".txt"))
```

There are approximately `r format(n_total, big.mark=",")` words in the book. I use the word "approximate" because it is easy to count something that isn't a word. The word counts for individual chapters are

`r chapter_count`

